[build]
    functions = "Netlify/Functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."chat"]
  timeout = 26

# Trigger deploy


[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "AIzaSyAtW-rocD37V23HGwA6xqwgxMFjhpRJMg4"
